Config = {}
Config.UseTarget = GetConvar('UseTarget', 'false') == 'true'

-- Deliveries
Config.ShopsInvJsonFile = './json/shops-inventory.json'
Config.TruckDeposit = 125
Config.MaxDeliveries = 20
Config.DeliveryPrice = 500
Config.RewardItem = 'cryptostick'
Config.Fuel = 'LegacyFuel'

Config.DeliveryLocations = {
    ['main'] = { label = 'GO Postal', coords = vector4(69.0862, 127.6753, 79.2123, 156.7736) },
    ['vehicleWithdraw'] = vector4(71.9318, 120.8389, 79.0823, 160.5110),
    ['vehicleDeposit'] = vector3(62.7282, 124.9846, 79.0926),
    ['stores'] = {} -- auto generated
}

Config.Vehicles = {
    ['boxville2'] = { ['label'] = 'Boxville StepVan', ['cargodoors'] = { [0] = 2, [1] = 3 }, ['trunkpos'] = 1.5 },
}

Config.Products = {
    ['frisbee'] = {
        { name = 'frisbee',    price = 5,  amount = 50 },
        { name = 'frisbee_r', price = 5, amount = 50 },
        { name = 'frisbee_g',   price = 5, amount = 50 },
        { name = 'frisbee_b',    price = 5,  amount = 50 },
        { name = 'frisbee_y', price = 5, amount = 50 },
    },
    ['burgers'] = {
        { name = 'burger',    price = 50,  amount = 50 },
        { name = 'cheeseburger', price = 50, amount = 50 },
        { name = 'doublecheeseburger',   price = 50, amount = 50 },
        { name = 'fries', price = 50, amount = 50 },
        { name = 'kurkakola', price = 50, amount = 50 },
    },
    ['normal'] = {
        { name = 'twerks_candy',         price = 2,   amount = 50 },
        { name = 'snikkel_candy',  price = 2,   amount = 50 },
        { name = 'jollyrancherbag',     price = 3,   amount = 50 },
        { name = 'tosti',  price = 5,   amount = 50 },
        { name = 'sandwich', price = 5,   amount = 50 },
        { name = 'water_bottle',      price = 3,   amount = 50 },
        { name = 'grapejuice',          price = 3,   amount = 50 },
        { name = 'kurkakola',       price = 3,  amount = 50 },
        { name = 'sprunk',         price = 3,  amount = 50 },
        { name = 'sprite',       price = 3, amount = 50 },
        { name = 'redbull',       price = 10,   amount = 50 },
        { name = 'beer', price = 7,   amount = 50 },
        { name = 'wine',         price = 12,   amount = 50 },
        { name = 'lighter',  price = 2,   amount = 50 },
        { name = 'tobacco',     price = 2,   amount = 50 },
        { name = 'rolling_paper',  price = 2,   amount = 50 },
        { name = 'mdwoods', price = 2,   amount = 50 },
        { name = 'bluntwrap',      price = 2,   amount = 50 },
        { name = 'redwoodpack',          price = 10,   amount = 50 },
        { name = 'yukonpack',       price = 10,  amount = 50 },
        { name = '69brandpack',         price = 10,  amount = 50 },
        { name = 'debonairepack',       price = 10, amount = 50 },
        { name = 'vape',       price = 25,   amount = 50 },
        { name = 'vapejuice', price = 25,   amount = 50 },
        { name = 'foamcup',       price = 1, amount = 50 },
        { name = 'leancup',       price = 1,   amount = 50 },
        { name = 'newspaper', price = 5,   amount = 50 },
    },
    ['liquor'] = {
        { name = 'wine',    price = 7,  amount = 50 },
        { name = 'beer', price = 7, amount = 50 },
        { name = 'whiskey',   price = 10, amount = 50 },
        { name = 'vodka',    price = 12,  amount = 50 },
        { name = 'bacardi', price = 10, amount = 50 },
        { name = 'hennessey',   price = 12, amount = 50 },
        { name = 'tequila',   price = 10, amount = 50 },
    },
    ['hardware'] = {
        { name = 'lockpick',          price = 200, amount = 50 },
        { name = 'briefcaselockpicker',     price = 200, amount = 50 },
        { name = 'screwdriver',     price = 250, amount = 50 },
        { name = 'screwdriverset',         price = 350, amount = 50 },
        { name = 'cleanershovel',    price = 750, amount = 50 },
        { name = 'blowtorch',             price = 1000, amount = 50 },
        { name = 'torque_wrench',             price = 500, amount = 50 },
        { name = 'drill',        price = 1000,  amount = 50 },
        { name = 'eblower',         price = 500,  amount = 50 },
        { name = 'carjack',         price = 1000,  amount = 50 },
        { name = 'singlepress',         price = 750,  amount = 50 },
        { name = 'dualpress',         price = 750,  amount = 50 },
        { name = 'triplepress',            price = 750, amount = 50 },
        { name = 'quadpress',       price = 750, amount = 50 },
        { name = 'pickaxe',         price = 100, amount = 50 },
        { name = 'minningdrill',          price = 8000, amount = 50 },
        { name = 'minninglaser',     price = 50000, amount = 50 },
        { name = 'drillbit',     price = 50, amount = 50 },
        { name = 'goldpan',         price = 50, amount = 50 },
        { name = 'weapon_knuckle',    price = 250, amount = 50 },
        { name = 'weapon_bottle',             price = 100, amount = 50 },
        { name = 'weapon_knife',             price = 250, amount = 50 },
        { name = 'weapon_dagger',        price = 250,  amount = 50 },
        { name = 'weapon_switchblade',         price = 250,  amount = 50 },
        { name = 'weapon_machete',         price = 250,  amount = 50 },
        { name = 'weapon_hammer',         price = 100,  amount = 50 },
        { name = 'weapon_wrench',         price = 100,  amount = 50 },
        { name = 'weapon_crobar',            price = 100, amount = 50 },
        { name = 'weapon_battleaxe',       price = 750, amount = 50 },
        { name = 'weapon_golfclub', price = 100, amount = 50 },
        { name = 'weapon_poolcue',          price = 100, amount = 50 },
        { name = 'weapon_bat',     price = 250, amount = 50 },
        { name = 'weapon_hatchet',     price = 250, amount = 50 },
        { name = 'weapon_stonehatchet',         price = 1000, amount = 50 },
        { name = 'weapon_katana',    price = 1000, amount = 50 },
        { name = 'weapon_sledgehammer',             price = 1000, amount = 50 },
        { name = 'firework1',         price = 50,  amount = 50 },
        { name = 'firework2',         price = 50,  amount = 50 },
        { name = 'firework3',         price = 50,  amount = 50 },
        { name = 'firework4',         price = 50,  amount = 50 },
    },
    ['weedshop'] = {
        { name = 'joint',          price = 10,  amount = 50 },
        { name = 'weedgrinder', price = 2, amount = 50 },
        { name = 'butane', price = 2, amount = 50 },
        { name = 'butanetorch', price = 2, amount = 50 },
        { name = 'dabrig', price = 2, amount = 50 },
        { name = 'rolling_paper',  price = 2,   amount = 50 },
        { name = 'empty_weed_bag', price = 2,   amount = 50 },
        { name = 'weed_nutrition', price = 20,  amount = 50 },
    },
    ['backpacks'] = {
        { name = 'holster', price = 200, amount = 50 },
        { name = 'backpack1',   price = 200,  amount = 50 },
        { name = 'backpack2', price = 300, amount = 50 },
        { name = 'duffle1',   price = 300,  amount = 50 },
        { name = 'briefcase', price = 300, amount = 50 },
    },
    ['leisureshop'] = {
        { name = 'fishingbait',   price = 5, amount = 50 },
        { name = 'fishingrod',  price = 500,   amount = 50 },
        { name = 'skateboard', price = 600, amount = 50 },
        { name = 'binoculars', price = 50,  amount = 50 },
        { name = 'parachute',   price = 2500, amount = 50 },
        { name = 'diving_fill',  price = 500,   amount = 50 },
        { name = 'diving_gear', price = 2500, amount = 50 },
        { name = 'jerry_can', price = 200,  amount = 50 },
    },
    ['weapons'] = {
        { name = 'pistol_ammo',          price = 250,  amount = 250, requiredLicense = 'weapon' },
        { name = 'weapon_flaregun',        price = 2500, amount = 5,   requiredLicense = 'weapon' },
        { name = 'weapon_gadgetpistol',     price = 2500, amount = 5,   requiredLicense = 'weapon' },
        { name = 'weapon_snspistol', price = 2500, amount = 5,   requiredLicense = 'weapon' },
        { name = 'weapon_ceramicpistol',         price = 1500,  amount = 250, requiredLicense = 'weapon' },
        { name = 'weapon_pistolxm3',           price = 1500,  amount = 250, requiredLicense = 'weapon' },
        { name = 'weapon_combatpistol',       price = 1500,  amount = 250, requiredLicense = 'weapon' },
        { name = 'weapon_pistol',         price = 2500,  amount = 250, requiredLicense = 'weapon' },
        { name = 'weapon_pistol50',           price = 4000,  amount = 250, requiredLicense = 'weapon' },
        { name = 'weapon_vintagepistol',       price = 4000,  amount = 250, requiredLicense = 'weapon' },
        { name = 'weapon_heavypistol',         price = 4000,  amount = 250, requiredLicense = 'weapon' },
        { name = 'weapon_marksmanpistol',           price = 1500,  amount = 250, requiredLicense = 'weapon' },
        { name = 'weapon_fnx45',       price = 1500,  amount = 250, requiredLicense = 'weapon' },
        { name = 'weapon_m1911',         price = 1500,  amount = 250, requiredLicense = 'weapon' },
        { name = 'weapon_glock18c',           price = 1500,  amount = 250, requiredLicense = 'weapon' },
        { name = 'weapon_glock22',       price = 1500,  amount = 250, requiredLicense = 'weapon' },
        { name = 'weapon_de',         price = 4000,  amount = 250, requiredLicense = 'weapon' },
        { name = 'weapon_revolver',           price = 4000,  amount = 250, requiredLicense = 'weapon' },
        { name = 'weapon_doubleaction',       price = 2500,  amount = 250, requiredLicense = 'weapon' },
        { name = 'weapon_navyrevolver',       price = 2500,  amount = 250, requiredLicense = 'weapon' },

    },
    ['jewler'] = {
        { name = 'chain_bdb',     price = 500000, amount = 50 },
        { name = 'chain_cp1', price = 100000, amount = 50 },
        { name = 'chain_cp2',     price = 100000, amount = 50 },
        { name = 'chain_skull', price = 100000, amount = 50 },
        { name = 'chain_skull2',     price = 100000, amount = 50 },
        { name = 'chain_skull3', price = 100000, amount = 50 },
        { name = 'chain_skull4',     price = 100000, amount = 50 },
        { name = 'chain_skull5', price = 100000, amount = 50 },
        { name = 'chain_skull6',     price = 100000, amount = 50 },
        { name = 'chain_skull7', price = 100000, amount = 50 },
        { name = 'chain_snake',     price = 100000, amount = 50 },
        { name = 'chain_au1', price = 100000, amount = 50 },
        { name = 'chain_au2',     price = 100000, amount = 50 },
        { name = 'chain_au3', price = 100000, amount = 50 },
        { name = 'chain_au4',     price = 100000, amount = 50 },
        { name = 'chain_au5', price = 100000, amount = 50 },
        { name = 'chain_au6',     price = 100000, amount = 50 },
        { name = 'chain_au7', price = 100000, amount = 50 },
        { name = 'chain_au8',     price = 100000, amount = 50 },
        { name = 'chain_au9', price = 100000, amount = 50 },
        { name = 'chain_au10',     price = 100000, amount = 50 },
        { name = 'chain_au11', price = 100000, amount = 50 },
        { name = 'chain_au12',     price = 100000, amount = 50 },
        { name = 'chain_au13', price = 100000, amount = 50 },
        { name = 'chain_au14',     price = 100000, amount = 50 },
        { name = 'chain_au15', price = 100000, amount = 50 },
        { name = 'chain_au16',     price = 100000, amount = 50 },
        { name = 'chain_v', price = 100000, amount = 50 },
        { name = 'chain_v1',     price = 100000, amount = 50 },
        { name = 'chain_v2', price = 100000, amount = 50 },
        { name = 'chain_nocap',     price = 100000, amount = 50 },
        { name = 'chain_link', price = 100000, amount = 50 },
    },
    ['mechshop'] = {
        { name = 'stashkey',     price = 10000, amount = 50 },
        { name = 'cleaningkit', price = 150, amount = 50 },
        { name = 'tirerepairkit',     price = 150, amount = 50 },
        { name = 'repairkit', price = 250, amount = 50 },
        { name = 'advancedrepairkit',     price = 500, amount = 50 },
        { name = 'driftchipbox', price = 10000, amount = 50 },
    },
    ['phone'] = {
        { name = 'fitbit',     price = 400, amount = 50 },
        { name = 'phone', price = 1000, amount = 50 },
        { name = 'cokeburner',     price = 1000, amount = 50 },
        { name = 'crackburner', price = 1000, amount = 50 },
        { name = 'heroinburner',     price = 1000, amount = 50 },
        { name = 'lsdburner', price = 1000, amount = 50 },
        { name = 'xtcburner',     price = 1000, amount = 50 },
        { name = 'laptop', price = 10000, amount = 50 },
    },
    ['meds'] = {
        { name = 'bandage',     price = 100, amount = 50 },
        { name = 'walkstick', price = 150, amount = 50 },
        { name = 'emptyvial',     price = 5, amount = 50 },
        { name = 'needle', price = 5, amount = 50 },
        { name = 'tab_paper',     price = 50, amount = 50 },
        { name = 'suicidepill', price = 250, amount = 50 },
        { name = 'fakesuicidepill',     price = 150, amount = 50 },
        { name = 'isosafrole', price = 25, amount = 50 },
        { name = 'mdp2p', price = 25, amount = 50 },
    },
    ['blackmarket'] = {
        { name = 'security_card_01',  price = 5000, amount = 50 },
        { name = 'security_card_02',  price = 5000, amount = 50 },
        { name = 'advanced_lockpick', price = 5000, amount = 50 },
        { name = 'electronickit',     price = 5000, amount = 50 },
        { name = 'gatecrack',         price = 5000, amount = 50 },
        { name = 'thermite',          price = 5000, amount = 50 },
        { name = 'trojan_usb',        price = 5000, amount = 50 },
        { name = 'radioscanner',      price = 5000, amount = 50 },
        { name = 'cryptostick',       price = 5000, amount = 50 },
        { name = 'joint',             price = 5000, amount = 50 },
        { name = 'cokebaggy',         price = 5000, amount = 50 },
        { name = 'crack_baggy',       price = 5000, amount = 50 },
        { name = 'xtcbaggy',          price = 5000, amount = 50 },
        { name = 'coke_brick',        price = 5000, amount = 50 },
        { name = 'weed_brick',        price = 5000, amount = 50 },
        { name = 'coke_small_brick',  price = 5000, amount = 50 },
        { name = 'oxy',               price = 5000, amount = 50 },
        { name = 'meth',              price = 5000, amount = 50 },
        { name = 'weed_whitewidow',   price = 5000, amount = 50 },
        { name = 'weed_skunk',        price = 5000, amount = 50 },
        { name = 'weed_purplehaze',   price = 5000, amount = 50 },
        { name = 'weed_ogkush',       price = 5000, amount = 50 },
        { name = 'weed_amnesia',      price = 5000, amount = 50 },
        { name = 'weed_ak47',         price = 5000, amount = 50 },
        { name = 'markedbills',       price = 5000, amount = 50, info = { worth = 5000 } },
    },
    ['prison'] = {
        { name = 'sandwich',     price = 4, amount = 50 },
        { name = 'water_bottle', price = 4, amount = 50 },
    },
    ['police'] = {
        { name = 'weapon_pistol',       price = 0, amount = 50, info = { attachments = { { component = 'COMPONENT_AT_PI_FLSH', label = 'Flashlight' } } } },
        { name = 'weapon_stungun',      price = 0, amount = 50, info = { attachments = { { component = 'COMPONENT_AT_AR_FLSH', label = 'Flashlight' } } } },
        { name = 'weapon_pumpshotgun',  price = 0, amount = 50, info = { attachments = { { component = 'COMPONENT_AT_AR_FLSH', label = 'Flashlight' } } } },
        { name = 'weapon_smg',          price = 0, amount = 50, info = { attachments = { { component = 'COMPONENT_AT_SCOPE_MACRO_02', label = '1x Scope' }, { component = 'COMPONENT_AT_AR_FLSH', label = 'Flashlight' } } } },
        { name = 'weapon_carbinerifle', price = 0, amount = 50, info = { attachments = { { component = 'COMPONENT_AT_AR_FLSH', label = 'Flashlight' }, { component = 'COMPONENT_AT_SCOPE_MEDIUM', label = '3x Scope' } } } },
        { name = 'weapon_nightstick',   price = 0, amount = 50 },
        { name = 'weapon_flashlight',   price = 0, amount = 50 },
        { name = 'pistol_ammo',         price = 0, amount = 50 },
        { name = 'smg_ammo',            price = 0, amount = 50 },
        { name = 'shotgun_ammo',        price = 0, amount = 50 },
        { name = 'rifle_ammo',          price = 0, amount = 50 },
        { name = 'handcuffs',           price = 0, amount = 50 },
        { name = 'empty_evidence_bag',  price = 0, amount = 50 },
        { name = 'police_stormram',     price = 0, amount = 50 },
        { name = 'armor',               price = 0, amount = 50 },
        { name = 'radio',               price = 0, amount = 50 },
        { name = 'heavyarmor',          price = 0, amount = 50 },
    },
    ['ambulance'] = {
        { name = 'radio',                   price = 0, amount = 50 },
        { name = 'bandage',                 price = 0, amount = 50 },
        { name = 'painkillers',             price = 0, amount = 50 },
        { name = 'firstaid',                price = 0, amount = 50 },
        { name = 'weapon_flashlight',       price = 0, amount = 50 },
        { name = 'weapon_fireextinguisher', price = 0, amount = 50 },
    },
    ['mechanic'] = {
        { name = 'veh_toolbox',       price = 5000, amount = 50 },
        { name = 'veh_armor',         price = 5000, amount = 50 },
        { name = 'veh_brakes',        price = 5000, amount = 50 },
        { name = 'veh_engine',        price = 5000, amount = 50 },
        { name = 'veh_suspension',    price = 5000, amount = 50 },
        { name = 'veh_transmission',  price = 5000, amount = 50 },
        { name = 'veh_turbo',         price = 5000, amount = 50 },
        { name = 'veh_interior',      price = 5000, amount = 50 },
        { name = 'veh_exterior',      price = 5000, amount = 50 },
        { name = 'veh_wheels',        price = 5000, amount = 50 },
        { name = 'veh_neons',         price = 5000, amount = 50 },
        { name = 'veh_xenons',        price = 5000, amount = 50 },
        { name = 'veh_tint',          price = 5000, amount = 50 },
        { name = 'veh_plates',        price = 5000, amount = 50 },
        { name = 'nitrous',           price = 5000, amount = 50 },
        { name = 'tunerlaptop',       price = 5000, amount = 50 },
        { name = 'repairkit',         price = 5000, amount = 50 },
        { name = 'advancedrepairkit', price = 5000, amount = 50 },
        { name = 'tirerepairkit',     price = 5000, amount = 50 },
    },
    -- ['greeneats'] = {
    --     { name = 'cocktailglass',          price = 1, amount = 50 },
    --     { name = 'drinkglass',     price = 1, amount = 250 },
    --     { name = 'emptycoffeecup',     price = 1, amount = 250 },
    --     { name = 'mug',         price = 1, amount = 50 },
    --     { name = 'plasticcup',    price = 1, amount = 50 },
    --     { name = 'shotglass',             price = 1, amount = 50 },
    --     { name = 'smoothiecup',             price = 1, amount = 50 },
    --     { name = 'softsdrinkcup',        price = 1,  amount = 50 },
    --     { name = 'egg',         price = 1,  amount = 50 },
    --     { name = 'milk',         price = 1,  amount = 50 },
    --     { name = 'mdbutter',         price = 1,  amount = 50 },
    --     { name = 'flour',         price = 1,  amount = 50 },
    --     { name = 'sugar',            price = 1, amount = 150 },
    --     { name = 'creamer',       price = 1, amount = 150 },
    --     { name = 'crushedice',         price = 1, amount = 50 },
    --     { name = 'coffeebeans',          price = 1, amount = 50 },
    --     { name = 'decafcoffeebeans',     price = 1, amount = 250 },
    --     { name = 'teabag',     price = 1, amount = 250 },
    --     { name = 'chocolate',         price = 1, amount = 50 },
    --     { name = 'mint',    price = 1, amount = 50 },
    --     { name = 'pistachio',             price = 1, amount = 50 },
    --     { name = 'vanilla',             price = 1, amount = 50 },
    --     { name = 'toffee',        price = 1,  amount = 50 },
    --     { name = 'caramel',         price = 1,  amount = 50 },
    --     { name = 'oreo',         price = 1,  amount = 50 },
    --     { name = 'dough',         price = 1,  amount = 50 },
    --     { name = 'cookiedough',         price = 1,  amount = 50 },
    --     { name = 'muffinmix',            price = 1, amount = 150 },
    --     { name = 'gelatine',       price = 1, amount = 150 },
    --     { name = 'browniemix', price = 1, amount = 50 },
    --     { name = 'pancakemix',          price = 1, amount = 50 },
    --     { name = 'smoothiemix',     price = 1, amount = 250 },
    --     { name = 'softscoopmix',     price = 1, amount = 250 },
    --     { name = 'bakingsoda',         price = 1, amount = 50 },
    --     { name = 'pepperseasoning',    price = 1, amount = 50 },
    --     { name = 'salt',             price = 1, amount = 50 },
    --     { name = 'ketchup',         price = 1,  amount = 50 },
    --     { name = 'mayo',         price = 1,  amount = 50 },
    --     { name = 'mustard',         price = 1,  amount = 50 },
    --     { name = 'hotsauce',         price = 1,  amount = 50 },
    --     { name = 'mildsauce',          price = 1, amount = 50 },
    --     { name = 'ranch',     price = 1, amount = 250 },
    --     { name = 'tartarsauce',     price = 1, amount = 250 },
    --     { name = 'alfredosauce',         price = 1, amount = 50 },
    --     { name = 'pastasauce',    price = 1, amount = 50 },
    --     { name = 'pizzasauce',             price = 1, amount = 50 },
    --     { name = 'redsauce',         price = 1,  amount = 50 },
    --     { name = 'refriedbeans',         price = 1,  amount = 50 },
    --     { name = 'chilli',         price = 1,  amount = 50 },
    --     { name = 'cheesesauce',         price = 1,  amount = 50 },
    --     { name = 'creamcheese',          price = 1, amount = 50 },
    --     { name = 'macaroni',     price = 1, amount = 250 },
    --     { name = 'spaghetti',     price = 1, amount = 250 },
    --     { name = 'tortillachips',         price = 1, amount = 50 },
    --     { name = 'tortillas',    price = 1, amount = 50 },
    --     { name = 'bigtortillas',             price = 1, amount = 50 },
    --     { name = 'hardtacoshell',         price = 1,  amount = 50 },
    --     { name = 'biscuit',         price = 1,  amount = 50 },
    --     { name = 'hotdogbun',         price = 1,  amount = 50 },
    --     { name = 'burgerbun',         price = 1,  amount = 50 },
    --     { name = 'croissant',          price = 1, amount = 50 },
    --     { name = 'bagel',     price = 1, amount = 250 },
    --     { name = 'loafbread',     price = 1, amount = 250 },
    --     { name = 'bread',         price = 1, amount = 50 },
    --     { name = 'pizzadough',    price = 1, amount = 50 },
    --     { name = 'banana',             price = 1, amount = 50 },
    --     { name = 'grape',         price = 1,  amount = 50 },
    --     { name = 'kiwi',         price = 1,  amount = 50 },
    --     { name = 'lime',         price = 1,  amount = 50 },
    --     { name = 'watermelon',         price = 1,  amount = 50 },
    --     { name = 'orange',          price = 1, amount = 50 },
    --     { name = 'apple',     price = 1, amount = 250 },
    --     { name = 'strawberry',     price = 1, amount = 250 },
    --     { name = 'blueberry',         price = 1, amount = 50 },
    --     { name = 'cherry',    price = 1, amount = 50 },
    --     { name = 'lemon',             price = 1, amount = 50 },
    --     { name = 'pineapple',         price = 1,  amount = 50 },
    --     { name = 'coconut',         price = 1,  amount = 50 },
    --     { name = 'lettuce',         price = 1,  amount = 50 },
    --     { name = 'potato',         price = 1,  amount = 50 },
    --     { name = 'mushroom',          price = 1, amount = 50 },
    --     { name = 'tomato',     price = 1, amount = 250 },
    --     { name = 'blackolives',     price = 1, amount = 250 },
    --     { name = 'cucumbers',         price = 1, amount = 50 },
    --     { name = 'jalepeno',    price = 1, amount = 50 },
    --     { name = 'onion',             price = 1, amount = 50 },
    --     { name = 'pepper',         price = 1,  amount = 50 },
    --     { name = 'pepperonimeat',         price = 1,  amount = 50 },
    --     { name = 'hardsalami',         price = 1,  amount = 50 },
    --     { name = 'cheeseblock',         price = 1,  amount = 50 },
    --     { name = 'parmesancheese',          price = 1, amount = 50 },
    --     { name = 'mozarellablock',     price = 1, amount = 250 },
    --     { name = 'tuna',     price = 1, amount = 250 },
    --     { name = 'rawfish',         price = 1, amount = 50 },
    --     { name = 'rawhotdog',    price = 1, amount = 50 },
    --     { name = 'bacon',             price = 1, amount = 50 },
    --     { name = 'rawsausage',         price = 1,  amount = 50 },
    --     { name = 'meat_pig',         price = 1,  amount = 50 },
    --     { name = 'uncookedthinsteak',         price = 1,  amount = 50 },
    --     { name = 'rawsteak',         price = 1,  amount = 50 },
    --     { name = 'meat_chicken',          price = 1, amount = 50 },
    --     { name = 'chickenwings',     price = 1, amount = 250 },
    --     { name = 'wholechicken',     price = 1, amount = 250 },
    --     { name = 'rawgroundbeef',         price = 1, amount = 50 },
    --     { name = 'blueraspberrysyrup',    price = 1, amount = 50 },
    --     { name = 'bubblegumsyrup',             price = 1, amount = 50 },
    --     { name = 'butterscotchsyrup',         price = 1,  amount = 50 },
    --     { name = 'cherrysyrup',         price = 1,  amount = 50 },
    --     { name = 'grapesyrup',         price = 1,  amount = 50 },
    --     { name = 'lemonlimesyrup',         price = 1,  amount = 50 },
    --     { name = 'orangesyrup',          price = 1, amount = 50 },
    --     { name = 'saltedcaramelsyrup',     price = 1, amount = 250 },
    --     { name = 'strawberrysyrup',     price = 1, amount = 250 },
    --     { name = 'tropicalsyrup',         price = 1, amount = 50 },
    --     { name = 'pepperseasoning',    price = 1, amount = 50 },
    -- }
}

Config.Locations = {
    -- gg-frisbeegolf
    ['frisbeeshop'] = {
        ['label'] = 'Frisbee Shop',
        ['coords'] = vector4(279.3, 6790.43, 15.94, 270.37),
        ['ped'] = 'a_f_y_juggalo_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fa-solid fa-cart-shopping',
        ['targetLabel'] = 'Check Frisbees',
        ['products'] = Config.Products['frisbee'],
        ['showblip'] = true,
        ['blipsprite'] = 540,
        ['blipscale'] = 0.5,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(26.45, -1315.51, 29.62, 0.07),
        ['useStock'] = true
    },

    -- 24/7 Locations
    ['247supermarket'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(24.47, -1346.62, 29.5, 271.66),
        ['ped'] = 'a_f_y_indian_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(26.45, -1315.51, 29.62, 0.07),
        ['useStock'] = true
    },

    ['247supermarket2'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(-3039.54, 584.38, 7.91, 17.27),
        ['ped'] = 'a_f_y_indian_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-3047.95, 590.71, 7.62, 19.53)
    },

    ['247supermarket3'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(-3242.97, 1000.01, 12.83, 357.57),
        ['ped'] = 'a_f_y_indian_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-3245.76, 1005.25, 12.83, 269.45)
    },

    ['247supermarket4'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(1728.07, 6415.63, 35.04, 242.95),
        ['ped'] = 'a_f_y_indian_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(1741.76, 6419.61, 35.04, 6.83)
    },

    ['247supermarket5'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(1959.82, 3740.48, 32.34, 301.57),
        ['ped'] = 'a_f_y_indian_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(1963.81, 3750.09, 32.26, 302.46)
    },

    ['247supermarket6'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(549.13, 2670.85, 42.16, 99.39),
        ['ped'] = 'a_f_y_indian_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(541.54, 2663.53, 42.17, 120.51)
    },

    ['247supermarket7'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(2677.47, 3279.76, 55.24, 335.08),
        ['ped'] = 'a_f_y_indian_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(2662.19, 3264.95, 55.24, 168.55)
    },

    ['247supermarket8'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(2556.66, 380.84, 108.62, 356.67),
        ['ped'] = 'a_f_y_indian_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(2553.24, 399.73, 108.56, 344.86)
    },

    ['247supermarket9'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(372.66, 326.98, 103.57, 253.73),
        ['ped'] = 'a_f_y_indian_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(379.97, 357.3, 102.56, 26.42)
    },

    ['247supermarket10'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(2749.15, 3483.16, 55.67, 74.0),
        ['ped'] = 'a_f_y_indian_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(2704.68, 3457.21, 55.54, 176.28)
    },

    ['247supermarket11'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(247.53, -268.61, 54.04, 250.89),
        ['ped'] = 'a_f_y_indian_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(259.7, -245.61, 53.86, 251.33)
    },

    ['247supermarket12'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(159.8, 6640.97, 31.7, 220.16),
        ['ped'] = 'a_f_y_indian_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(160.96, 6629.66, 31.71, 42.36)
    },

    ['247supermarket13'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(-675.05, 5834.52, 17.33, 52.61),
        ['ped'] = 'a_f_y_indian_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-666.34, 5829.63, 17.33, 312.36)
    },

    ['247supermarket14'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(377.61, -1787.08, 29.52, 319.63),
        ['ped'] = 'a_f_y_indian_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(368.12, -1775.71, 29.07, 325.91)
    },

    ['247supermarket15'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(4506.6, -4609.16, 8.24, 12.65),
        ['ped'] = 'a_f_y_indian_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(368.12, -1775.71, 29.07, 325.91)
    },

    -- LTD Gasoline Locations
    ['ltdgasoline'] = {
        ['label'] = 'LTD Gasoline',
        ['coords'] = vector4(-47.02, -1758.23, 29.42, 45.05),
        ['ped'] = 'a_f_y_indian_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-40.51, -1747.45, 29.29, 326.39)
    },

    ['ltdgasoline2'] = {
        ['label'] = 'LTD Gasoline',
        ['coords'] = vector4(-706.06, -913.97, 19.22, 88.04),
        ['ped'] = 'a_f_y_indian_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-702.89, -917.44, 19.21, 181.96)
    },

    ['ltdgasoline3'] = {
        ['label'] = 'LTD Gasoline',
        ['coords'] = vector4(-1820.02, 794.03, 138.09, 135.45),
        ['ped'] = 'a_f_y_indian_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-1829.29, 801.49, 138.41, 41.39)
    },

    ['ltdgasoline4'] = {
        ['label'] = 'LTD Gasoline',
        ['coords'] = vector4(1164.71, -322.94, 69.21, 101.72),
        ['ped'] = 'a_f_y_indian_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(1160.62, -312.06, 69.28, 3.77)
    },

    ['ltdgasoline5'] = {
        ['label'] = 'LTD Gasoline',
        ['coords'] = vector4(1697.87, 4922.96, 42.06, 324.71),
        ['ped'] = 'a_f_y_indian_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(1702.68, 4917.28, 42.22, 139.27)
    },

    -- Rob's Liquor Locations
    ['robsliquor'] = {
        ['label'] = 'Rob\'s Liqour',
        ['coords'] = vector4(-1221.58, -908.15, 12.33, 35.49),
        ['ped'] = 'a_f_y_indian_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['liquor'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-1226.92, -901.82, 12.28, 213.26)
    },

    ['robsliquor2'] = {
        ['label'] = 'Rob\'s Liqour',
        ['coords'] = vector4(-1486.59, -377.68, 40.16, 139.51),
        ['ped'] = 'a_f_y_indian_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['liquor'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-1468.29, -387.61, 38.79, 220.13)
    },

    ['robsliquor3'] = {
        ['label'] = 'Rob\'s Liqour',
        ['coords'] = vector4(-2966.39, 391.42, 15.04, 87.48),
        ['ped'] = 'a_f_y_indian_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['liquor'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-2961.49, 376.25, 15.02, 111.41)
    },

    ['robsliquor4'] = {
        ['label'] = 'Rob\'s Liqour',
        ['coords'] = vector4(1165.17, 2710.88, 38.16, 179.43),
        ['ped'] = 'a_f_y_indian_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['liquor'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(1194.52, 2722.21, 38.62, 9.37)
    },

    ['robsliquor5'] = {
        ['label'] = 'Rob\'s Liqour',
        ['coords'] = vector4(1134.2, -982.91, 46.42, 277.24),
        ['ped'] = 'a_f_y_indian_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['liquor'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(1129.73, -989.27, 45.97, 280.98)
    },

    ['robsliquor6'] = {
        ['label'] = 'Rob\'s Liqour',
        ['coords'] = vector4(2313.55, 3958.58, 42.04, 222.59),
        ['ped'] = 'a_f_y_indian_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['liquor'],
        ['showblip'] = false,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(2296.24, 3921.07, 37.1, 41.24)
    },

    ['robsliquor7'] = {
        ['label'] = 'Rob\'s Liqour',
        ['coords'] = vector4(4466.37, -4463.71, 4.3, 201.36),
        ['ped'] = 'a_f_y_indian_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['liquor'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(776.01, -2986.86, 5.51, 272.19)
    },

    -- Hardware Store Locations
    ['hardware'] = {
        ['label'] = 'Hardware Store',
        ['coords'] = vector4(257.7, -281.61, 54.04, 40.22),
        ['ped'] = 'mp_f_bennymech_01',
        ['scenario'] = 'WORLD_HUMAN_CLIPBOARD',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-wrench',
        ['targetLabel'] = 'Open Hardware Store',
        ['products'] = Config.Products['hardware'],
        ['showblip'] = true,
        ['blipsprite'] = 402,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(259.7, -245.61, 53.86, 251.33)
    },

    ['hardware2'] = {
        ['label'] = 'Hardware Store',
        ['coords'] = vector4(2733.32, 3496.92, 55.67, 161.01),
        ['ped'] = 'mp_f_bennymech_01',
        ['scenario'] = 'WORLD_HUMAN_CLIPBOARD',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-wrench',
        ['targetLabel'] = 'Open Hardware Store',
        ['products'] = Config.Products['hardware'],
        ['showblip'] = true,
        ['blipsprite'] = 402,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(2704.68, 3457.21, 55.54, 176.28)
    },

    ['hardware3'] = {
        ['label'] = 'Hardware Store',
        ['coords'] = vector4(-10.89, 6499.19, 31.51, 47.47),
        ['ped'] = 'mp_f_bennymech_01',
        ['scenario'] = 'WORLD_HUMAN_CLIPBOARD',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-wrench',
        ['targetLabel'] = 'Hardware Store',
        ['products'] = Config.Products['hardware'],
        ['showblip'] = true,
        ['blipsprite'] = 402,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-4.21, 6507.61, 31.46, 224.34)
    },

    -- Ammunation Locations
    ['ammunation'] = {
        ['label'] = 'Ammunation',
        ['type'] = 'weapon',
        ['coords'] = vector4(-661.96, -933.53, 21.83, 177.05),
        ['ped'] = 'mp_f_chbar_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Ammunation',
        ['products'] = Config.Products['weapons'],
        ['showblip'] = true,
        ['blipsprite'] = 110,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-660.61, -938.14, 21.83, 167.22)
    },
    ['ammunation2'] = {
        ['label'] = 'Ammunation',
        ['type'] = 'weapon',
        ['coords'] = vector4(809.68, -2159.13, 29.62, 1.43),
        ['ped'] = 'mp_f_chbar_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Ammunation',
        ['products'] = Config.Products['weapons'],
        ['showblip'] = true,
        ['blipsprite'] = 110,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(820.97, -2146.7, 28.71, 359.98)
    },
    ['ammunation3'] = {
        ['label'] = 'Ammunation',
        ['type'] = 'weapon',
        ['coords'] = vector4(1692.67, 3761.38, 34.71, 227.65),
        ['ped'] = 'mp_f_chbar_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Ammunation',
        ['products'] = Config.Products['weapons'],
        ['showblip'] = true,
        ['blipsprite'] = 110,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(1687.17, 3755.47, 34.34, 163.69)
    },
    ['ammunation4'] = {
        ['label'] = 'Ammunation',
        ['type'] = 'weapon',
        ['coords'] = vector4(-331.23, 6085.37, 31.45, 228.02),
        ['ped'] = 'mp_f_chbar_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Ammunation',
        ['products'] = Config.Products['weapons'],
        ['showblip'] = true,
        ['blipsprite'] = 110,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-341.72, 6098.49, 31.32, 11.05)
    },
    ['ammunation5'] = {
        ['label'] = 'Ammunation',
        ['type'] = 'weapon',
        ['coords'] = vector4(253.63, -51.02, 69.94, 72.91),
        ['ped'] = 'mp_f_chbar_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Ammunation',
        ['products'] = Config.Products['weapons'],
        ['showblip'] = true,
        ['blipsprite'] = 110,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(249.0, -50.64, 69.94, 60.71)
    },
    ['ammunation6'] = {
        ['label'] = 'Ammunation',
        ['type'] = 'weapon',
        ['coords'] = vector4(23.0, -1105.67, 29.8, 162.91),
        ['ped'] = 'mp_f_chbar_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Ammunation',
        ['products'] = Config.Products['weapons'],
        ['showblip'] = true,
        ['blipsprite'] = 110,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-5.82, -1107.48, 29.0, 164.32)
    },
    ['ammunation7'] = {
        ['label'] = 'Ammunation',
        ['type'] = 'weapon',
        ['coords'] = vector4(2567.48, 292.59, 108.73, 349.68),
        ['ped'] = 'mp_f_chbar_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Ammunation',
        ['products'] = Config.Products['weapons'],
        ['showblip'] = true,
        ['blipsprite'] = 110,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(2578.77, 285.53, 108.61, 277.2)
    },
    ['ammunation8'] = {
        ['label'] = 'Ammunation',
        ['type'] = 'weapon',
        ['coords'] = vector4(-1118.59, 2700.05, 18.55, 221.89),
        ['ped'] = 'mp_f_chbar_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Ammunation',
        ['products'] = Config.Products['weapons'],
        ['showblip'] = true,
        ['blipsprite'] = 110,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-1127.67, 2708.18, 18.8, 41.76)
    },
    ['ammunation9'] = {
        ['label'] = 'Ammunation',
        ['type'] = 'weapon',
        ['coords'] = vector4(841.92, -1035.32, 28.19, 1.56),
        ['ped'] = 'mp_f_chbar_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Ammunation',
        ['products'] = Config.Products['weapons'],
        ['showblip'] = true,
        ['blipsprite'] = 110,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(847.83, -1020.36, 27.88, 88.29)
    },
    ['ammunation10'] = {
        ['label'] = 'Ammunation',
        ['type'] = 'weapon',
        ['coords'] = vector4(-1304.19, -395.12, 36.7, 75.03),
        ['ped'] = 'mp_f_chbar_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Ammunation',
        ['products'] = Config.Products['weapons'],
        ['showblip'] = true,
        ['blipsprite'] = 110,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-1302.44, -385.23, 36.62, 303.79)
    },
    ['ammunation11'] = {
        ['label'] = 'Ammunation',
        ['type'] = 'weapon',
        ['coords'] = vector4(-3173.31, 1088.85, 20.84, 244.18),
        ['ped'] = 'mp_f_chbar_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Ammunation',
        ['products'] = Config.Products['weapons'],
        ['showblip'] = true,
        ['blipsprite'] = 110,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-3183.6, 1084.35, 20.84, 68.13)
    },

    ['ammunation12'] = {
        ['label'] = 'Ammunation',
        ['type'] = 'weapon',
        ['coords'] = vector4(4518.82, -4492.38, 8.32, 145.09),
        ['ped'] = 'mp_f_chbar_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Ammunation',
        ['products'] = Config.Products['weapons'],
        ['showblip'] = true,
        ['blipsprite'] = 110,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(776.01, -2986.86, 5.51, 272.19)
    },

    -- Weedshop Locations
    ['weedshop'] = {
        ['label'] = 'Smoke On The Water',
        ['coords'] = vector4(-1168.26, -1573.2, 4.66, 105.24),
        ['ped'] = 'a_f_y_hippy_01',
        ['scenario'] = 'WORLD_HUMAN_AA_SMOKE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-cannabis',
        ['targetLabel'] = 'Open Weed Shop',
        ['products'] = Config.Products['weedshop'],
        ['showblip'] = true,
        ['blipsprite'] = 140,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-1162.13, -1568.57, 4.39, 328.52)
    },

    ['weedshop2'] = {
        ['label'] = 'Smoke On The Water',
        ['coords'] = vector4(2751.62, 3488.77, 55.66, 61.88),
        ['ped'] = 'a_f_y_hippie_01',
        ['scenario'] = 'WORLD_HUMAN_AA_SMOKE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-cannabis',
        ['targetLabel'] = 'Open Weed Shop',
        ['products'] = Config.Products['weedshop'],
        ['showblip'] = true,
        ['blipsprite'] = 140,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(2704.68, 3457.21, 55.54, 176.28)
    },

    ['weedshop2'] = {
        ['label'] = 'Smoke On The Water',
        ['coords'] = vector4(234.82, -261.44, 54.04, 260.8),
        ['ped'] = 'a_f_y_hippie_01',
        ['scenario'] = 'WORLD_HUMAN_AA_SMOKE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-cannabis',
        ['targetLabel'] = 'Open Weed Shop',
        ['products'] = Config.Products['weedshop'],
        ['showblip'] = true,
        ['blipsprite'] = 140,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(259.7, -245.61, 53.86, 251.33)
    },

    -- Leisure Shop Locations
    ['leisureshop1'] = {
        ['label'] = 'Leisure Shop',
        ['coords'] = vector4(-1687.03, -1072.18, 13.15, 52.93),
        ['ped'] = 'a_f_y_runner_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_IMPATIENT',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-fish',
        ['targetLabel'] = 'Open Leisure Shop',
        ['products'] = Config.Products['leisureshop'],
        ['showblip'] = true,
        ['blipsprite'] = 94,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-1674.18, -1073.7, 13.15, 333.56)
    },

    ['leisureshop2'] = {
        ['label'] = 'Leisure Shop',
        ['coords'] = vector4(-1505.91, 1511.95, 115.29, 257.13),
        ['ped'] = 'a_f_y_runner_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-leaf',
        ['targetLabel'] = 'Open Leisure Shop',
        ['products'] = Config.Products['leisureshop'],
        ['showblip'] = true,
        ['blipsprite'] = 94,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-1507.64, 1505.52, 115.29, 262.2)
    },

    ['leisureshop3'] = {
        ['label'] = 'Leisure Shop',
        ['coords'] = vector4(2729.25, 3486.04, 55.67, 298.7),
        ['ped'] = 'a_f_y_runner_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-leaf',
        ['targetLabel'] = 'Open Leisure Shop',
        ['products'] = Config.Products['leisureshop'],
        ['showblip'] = true,
        ['blipsprite'] = 94,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(2704.68, 3457.21, 55.54, 176.28)
    },

    ['leisureshop4'] = {
        ['label'] = 'Leisure Shop',
        ['coords'] = vector4(240.53, -267.28, 54.04, 1.02),
        ['ped'] = 'a_f_y_runner_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-leaf',
        ['targetLabel'] = 'Open Leisure Shop',
        ['products'] = Config.Products['leisureshop'],
        ['showblip'] = true,
        ['blipsprite'] = 94,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(259.7, -245.61, 53.86, 251.33)
    },

    ['mechshop'] = {
        ['label'] = 'Mechanic Shop',
        ['coords'] = vector4(112.99, 6632.98, 31.97, 320.7),
        ['ped'] = 'mp_f_bennymech_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fa-solid fa-key',
        ['targetLabel'] = 'Buy Car Products',
        ['products'] = Config.Products['mechshop'],
        ['showblip'] = true,
        ['blipsprite'] = 369,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(133.47, 6633.08, 31.68, 136.32)
    },

    ['pharmacy1'] = {
        ['label'] = 'Pharmacy',
        ['coords'] = vector4(316.34, -587.24, 43.29, 197.76),
        ['ped'] = 's_f_y_scrubs_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fa-solid fa-syringe',
        ['targetLabel'] = 'Buy Medicine',
        ['products'] = Config.Products['meds'],
        ['showblip'] = true,
        ['blipsprite'] = 51,
        ['blipscale'] = 0.7,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(319.37, -560.21, 28.74, 204.07)
    },
    
    ['pharmacy2'] = {
        ['label'] = 'Pharmacy',
        ['coords'] = vector4(71.12, -813.1, 31.34, 267.13), 
        ['ped'] = 's_f_y_scrubs_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fa-solid fa-syringe',
        ['targetLabel'] = 'Buy Medicine',
        ['products'] = Config.Products['meds'],
        ['showblip'] = true,
        ['blipsprite'] = 51,
        ['blipscale'] = 0.7,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(39.75, -826.53, 31.13, 341.96)
    },

    ['pharmacy3'] = {
        ['label'] = 'Pharmacy',
        ['coords'] = vector4(-508.06, 292.48, 83.39, 173.75), 
        ['ped'] = 's_f_y_scrubs_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fa-solid fa-syringe',
        ['targetLabel'] = 'Buy Medicine',
        ['products'] = Config.Products['meds'],
        ['showblip'] = true,
        ['blipsprite'] = 51,
        ['blipscale'] = 0.7,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-500.74, 274.34, 83.23, 93.08)
    },

    ['phone1'] = {
        ['label'] = 'Digital Den',
        ['coords'] = vector4(2740.62, 3461.85, 55.67, 337.15), 
        ['ped'] = 'a_f_y_business_02',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fa-solid fa-syringe',
        ['targetLabel'] = 'Buy Electronics',
        ['products'] = Config.Products['phone'],
        ['showblip'] = true,
        ['blipsprite'] = 459,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(2704.68, 3457.21, 55.54, 176.28)
    },

    ['phone2'] = {
        ['label'] = 'Digital Den',
        ['coords'] = vector4(235.48, -265.47, 54.04, 350.94), 
        ['ped'] = 'a_f_y_business_02',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fa-solid fa-syringe',
        ['targetLabel'] = 'Buy Electronics',
        ['products'] = Config.Products['phone'],
        ['showblip'] = true,
        ['blipsprite'] = 459,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(259.7, -245.61, 53.86, 251.33)
    },

    ['phone3'] = {
        ['label'] = 'Digital Den',
        ['coords'] = vector4(74.34, -1403.71, 29.43, 0.63), 
        ['ped'] = 'a_f_y_business_02',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fa-solid fa-syringe',
        ['targetLabel'] = 'Buy Electronics',
        ['products'] = Config.Products['phone'],
        ['showblip'] = true,
        ['blipsprite'] = 459,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(86.17, -1391.08, 29.24, 185.68)
    },

    ['backpacks1'] = {
        ['label'] = 'Backpacks',
        ['coords'] = vector4(2738.01, 3473.99, 55.67, 87.87), 
        ['ped'] = 's_f_y_clubbar_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fa-solid fa-syringe',
        ['targetLabel'] = 'Buy Backpacks',
        ['products'] = Config.Products['backpacks'],
        ['showblip'] = true,
        ['blipsprite'] = 377,
        ['blipscale'] = 0.9,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(2704.68, 3457.21, 55.54, 176.28)
    },

    ['backpacks2'] = {
        ['label'] = 'Backpacks',
        ['coords'] = vector4(250.56, -264.98, 54.04, 160.67), 
        ['ped'] = 's_f_y_clubbar_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fa-solid fa-syringe',
        ['targetLabel'] = 'Buy Backpacks',
        ['products'] = Config.Products['backpacks'],
        ['showblip'] = true,
        ['blipsprite'] = 377,
        ['blipscale'] = 0.9,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(259.7, -245.61, 53.86, 251.33)
    },

    ['jewler1'] = {
        ['label'] = 'Jewlery',
        ['coords'] = vector4(-618.63, -228.2, 38.06, 128.72), 
        ['ped'] = 'mp_f_cardesign_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fa-solid fa-syringe',
        ['targetLabel'] = 'Buy Chains',
        ['products'] = Config.Products['jewler'],
        ['showblip'] = true,
        ['blipsprite'] = 617,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-675.43, -248.69, 36.44, 38.78)
    },

    ['jewler2'] = {
        ['label'] = 'Jewlery',
        ['coords'] = vector4(1652.31, 4880.05, 42.16, 3.8), 
        ['ped'] = 'mp_f_cardesign_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fa-solid fa-syringe',
        ['targetLabel'] = 'Buy Chains',
        ['products'] = Config.Products['jewler'],
        ['showblip'] = true,
        ['blipsprite'] = 617,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(1658.52, 4885.6, 42.01, 186.72)
    },

    ['jewler3'] = {
        ['label'] = 'Jewlery',
        ['coords'] = vector4(-383.73, 6046.15, 31.51, 218.93), 
        ['ped'] = 'mp_f_cardesign_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fa-solid fa-syringe',
        ['targetLabel'] = 'Buy Chains',
        ['products'] = Config.Products['jewler'],
        ['showblip'] = true,
        ['blipsprite'] = 617,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-396.26, 6031.53, 31.39, 47.37)
    },

    ['jewler4'] = {
        ['label'] = 'Jewlery',
        ['coords'] = vector4(-1369.4, -300.44, 43.7, 42.62), 
        ['ped'] = 'mp_f_cardesign_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fa-solid fa-syringe',
        ['targetLabel'] = 'Buy Chains',
        ['products'] = Config.Products['jewler'],
        ['showblip'] = true,
        ['blipsprite'] = 617,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-1382.28, -281.21, 43.02, 308.27)
    },

    -- ['greeneats'] = {
    --     ['label'] = 'Green Eats',
    --     ['coords'] = vector4(-1112.25, -1361.7, 5.04, 210.25), 
    --     ['ped'] = 'mp_f_weed_01',
    --     ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
    --     ['radius'] = 1.5,
    --     ['targetIcon'] = 'fa-solid fa-syringe',
    --     ['targetLabel'] = 'Buy Ingredients',
    --     ['products'] = Config.Products['greeneats'],
    --     ['showblip'] = true,
    --     ['blipsprite'] = 478,
    --     ['blipscale'] = 0.8,
    --     ['blipcolor'] = 0,
    --     ['delivery'] = vector4(-1109.04, -1373.5, 5.08, 114.27)
    -- },

    ['masterburger'] = {
        ['label'] = 'Master Burger',
        ['coords'] = vector4(97.35, -1425.28, 29.42, 323.73), 
        ['ped'] = 'g_f_y_families_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fa-solid fa-syringe',
        ['targetLabel'] = 'Buy Food',
        ['products'] = Config.Products['burgers'],
        ['showblip'] = true,
        ['blipsprite'] = 211,
        ['blipscale'] = 0.4,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(99.1, -1414.14, 29.21, 232.42)
    },

    ['police'] = {
        ['label'] = 'Police Shop',
        ['coords'] = vector4(461.8498, -981.0677, 30.6896, 91.5892),
        ['ped'] = 's_f_y_cop_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Armory',
        ['products'] = Config.Products['police'],
        ['delivery'] = vector4(459.0441, -1008.0366, 28.2627, 271.4695),
        ['requiredJob'] = 'police',
    },

    ['police2'] = {
        ['label'] = 'Police Shop',
        ['coords'] = vector4(-1627.71, -1024.3, 13.16, 225.65),
        ['ped'] = 's_f_y_cop_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Armory',
        ['products'] = Config.Products['police'],
        ['delivery'] = vector4(-1613.43, -1015.89, 13.12, 229.02),
        ['requiredJob'] = 'police',
    },

    ['police3'] = {
        ['label'] = 'Police Shop',
        ['coords'] = vector4(1844.34, 3692.23, 34.27, 280.89),
        ['ped'] = 's_f_y_cop_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Armory',
        ['products'] = Config.Products['police'],
        ['delivery'] = vector4(1868.75, 3692.68, 33.66, 27.29),
        ['requiredJob'] = 'police',
    },

    ['police4'] = {
        ['label'] = 'Police Shop',
        ['coords'] = vector4(-452.31, 6019.56, 31.75, 128.77),
        ['ped'] = 's_f_y_cop_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Armory',
        ['products'] = Config.Products['police'],
        ['delivery'] = vector4(-442.91, 6050.5, 31.34, 22.97),
        ['requiredJob'] = 'police',
    },

    ['police5'] = {
        ['label'] = 'Police Shop',
        ['coords'] = vector4(1727.68, 3027.66, 62.98, 250.75),
        ['ped'] = 's_f_y_cop_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Armory',
        ['products'] = Config.Products['police'],
        ['delivery'] = vector4(1719.46, 3035.66, 60.56, 194.94),
        ['requiredJob'] = 'police',
    },

    ['police6'] = {
        ['label'] = 'Police Shop',
        ['coords'] = vector4(1772.37, 2480.67, 45.85, 2.17),
        ['ped'] = 's_f_y_cop_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Armory',
        ['products'] = Config.Products['police'],
        ['delivery'] = vector4(1854.51, 2592.6, 45.67, 2.17),
        ['requiredJob'] = 'police',
    },

    ['police7'] = {
        ['label'] = 'Police Shop',
        ['coords'] = vector4(5128.45, -4703.17, 2.51, 325.6),
        ['ped'] = 's_f_y_cop_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Armory',
        ['products'] = Config.Products['police'],
        ['delivery'] = vector4(776.01, -2986.86, 5.51, 272.19),
        ['requiredJob'] = 'police',
    },

    ['ambulance'] = {
        ['label'] = 'Ambulance Shop',
        ['coords'] = vector4(309.93, -602.94, 43.29, 71.0820),
        ['ped'] = 's_f_y_scrubs_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-hand',
        ['targetLabel'] = 'Open Armory',
        ['products'] = Config.Products['ambulance'],
        ['delivery'] = vector4(283.5821, -614.8570, 43.3792, 159.2903),
        ['requiredJob'] = 'ambulance'
    },

    ['ambulance2'] = {
        ['label'] = 'Ambulance Shop',
        ['coords'] = vector4(1817.58, 3678.62, 34.28, 223.09),
        ['ped'] = 's_f_y_scrubs_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-hand',
        ['targetLabel'] = 'Open Armory',
        ['products'] = Config.Products['ambulance'],
        ['delivery'] = vector4(1808.21, 3665.06, 34.31, 23.39),
        ['requiredJob'] = 'ambulance'
    },

    ['ambulance3'] = {
        ['label'] = 'Ambulance Shop',
        ['coords'] = vector4(-256.76, 6330.26, 32.43, 320.2),
        ['ped'] = 's_f_y_scrubs_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-hand',
        ['targetLabel'] = 'Open Armory',
        ['products'] = Config.Products['ambulance'],
        ['delivery'] = vector4(-260.2, 6333.56, 32.43, 130.62),
        ['requiredJob'] = 'ambulance'
    },

    ['ambulance4'] = {
        ['label'] = 'Ambulance Shop',
        ['coords'] = vector4(4486.53, -4510.35, 4.18, 288.06),
        ['ped'] = 's_f_y_scrubs_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-hand',
        ['targetLabel'] = 'Open Armory',
        ['products'] = Config.Products['ambulance'],
        ['delivery'] = vector4(776.01, -2986.86, 5.51, 272.19),
        ['requiredJob'] = 'ambulance'
    },

    ['lsmechanic'] = {
        ['label'] = 'Mechanic Shop',
        ['coords'] = vector4(-320.89, -138.1, 39.01, 62.13),
        ['products'] = Config.Products['mechanic'],
        ['delivery'] = vector4(-362.09, -121.74, 38.7, 246.85),
        ['requiredJob'] = 'lsmechanic',
    },

    ['lsmechanic2'] = {   ---broken in sandy
        ['label'] = 'Mechanic Shop',
        ['coords'] = vector4(1189.36, 2641.00, 38.44, 0),
        ['products'] = Config.Products['mechanic'],
        ['delivery'] = vector4(1189.9852, 2651.1873, 37.8351, 317.7137),
        ['requiredJob'] = 'lsmechanic2'
    },

    ['airmechanic'] = {
        ['label'] = 'Mechanic Shop',
        ['coords'] = vector4(-1163.8, -2021.61, 13.18, 303.75),
        ['products'] = Config.Products['mechanic'],
        ['delivery'] = vector4(-1153.76, -1986.26, 13.16, 134.65),
        ['requiredJob'] = 'airmechanic'
    },

    ['lsmechanic3'] = {
        ['label'] = 'Mechanic Shop',
        ['coords'] = vector4(724.15, -1071.74, 23.13, 293.0),
        ['products'] = Config.Products['mechanic'],
        ['delivery'] = vector4(716.05, -1078.71, 22.28, 275.44),
        ['requiredJob'] = 'lsmechanic3',
    },

    ['delmechanic'] = {
        ['label'] = 'Mechanic Shop',
        ['coords'] = vector4(-1607.1, -842.5, 10.27, 49.34),
        ['products'] = Config.Products['mechanic'],
        ['delivery'] = vector4(-1634.78, -817.01, 10.11, 325.74),
        ['requiredJob'] = 'delmechanic'
    },

    ['sandymechanic'] = {
        ['label'] = 'Mechanic Shop',
        ['coords'] = vector4(2313.42, 3945.09, 37.1, 136.02),
        ['products'] = Config.Products['mechanic'],
        ['delivery'] = vector4(2295.78, 3921.87, 37.1, 31.4),
        ['requiredJob'] = 'sandymechanic'
    },

    ['cayomechanic'] = {
        ['label'] = 'Mechanic Shop',
        ['coords'] = vector4(5171.92, -4665.57, 2.56, 0),
        ['products'] = Config.Products['mechanic'],
        ['delivery'] = vector4(776.01, -2986.86, 5.51, 272.19),
        ['requiredJob'] = 'cayomechanic'
    },

    ['autoexoticmechanic'] = {
        ['label'] = 'Mechanic Shop',
        ['coords'] = vector4(542.31, -166.54, 57.68, 181.94),
        ['products'] = Config.Products['mechanic'],
        ['delivery'] = vector4(530.88, -168.79, 54.48, 356.45),
        ['requiredJob'] = 'autoexoticmechanic'
    },

    ['gangmechanic'] = {
        ['label'] = 'Mechanic Shop',
        ['coords'] = vector4(-2580.67, 1877.33, 167.77, 221.42),
        ['products'] = Config.Products['mechanic'],
        ['delivery'] = vector4(-2553.75, 1912.83, 168.99, 63.81),
        ['requiredJob'] = 'gangmechanic'
    },

    ['taximechanic'] = {
        ['label'] = 'Mechanic Shop',
        ['coords'] = vector4(891.42, -179.11, 74.7, 324.23),
        ['products'] = Config.Products['mechanic'],
        ['delivery'] = vector4(898.11, -133.52, 77.0, 236.27),
        ['requiredJob'] = 'taximechanic'
    },

    ['dealermechanic'] = {
        ['label'] = 'Mechanic Shop',
        ['coords'] = vector4(-39.47, -1082.44, 26.42, 251.82),
        ['products'] = Config.Products['mechanic'],
        ['delivery'] = vector4(-19.34, -1100.69, 26.67, 338.91),
        ['requiredJob'] = 'dealermechanic'
    },

    ['dealermechanic2'] = {
        ['label'] = 'Mechanic Shop',
        ['coords'] = vector4(78.67, 6558.3, 31.62, 126.13),
        ['products'] = Config.Products['mechanic'],
        ['delivery'] = vector4(95.52, 6559.27, 31.66, 49.7),
        ['requiredJob'] = 'dealermechanic2'
    },

    ['bennys'] = {
        ['label'] = 'Mechanic Shop',
        ['coords'] = vector4(-196.54, -1314.84, 31.28, 207.4),
        ['products'] = Config.Products['mechanic'],
        ['delivery'] = vector4(-195.31, -1307.73, 31.27, 268.67),
        ['requiredJob'] = 'bennys'
    },

    ['beeker'] = {
        ['label'] = 'Mechanic Shop',
        ['coords'] = vector4(98.0, 6619.26, 32.44, 316.45),
        ['products'] = Config.Products['mechanic'],
        ['delivery'] = vector4(127.63, 6627.5, 31.76, 134.73),
        ['requiredJob'] = 'beeker'
    },

    ['prison'] = {
        ['label'] = 'Canteen Shop',
        ['coords'] = vector4(1777.59, 2560.52, 44.62, 187.83),
        ['ped'] = false,
        ['products'] = Config.Products['prison'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(1845.8175, 2585.9312, 45.6721, 96.7577)
    },

    ['blackmarket'] = {
        ['label'] = 'Black Market',
        ['coords'] = vector4(-594.7032, -1616.3647, 33.0105, 170.6846),
        ['ped'] = 'csb_paige',
        ['scenario'] = 'WORLD_HUMAN_AA_SMOKE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-clipboard',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['blackmarket'],
        ['delivery'] = vector4(-428.6385, -1728.1962, 19.7838, 75.6646)
    },
}
